In [2]:
!mamba install pandas

mambajs 0.19.13

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas
Channels: emscripten-forge, conda-forge

Solving environment...
Solving took 3.363 seconds
  Name                          Version                       Build                         Channel
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
+ pandas                        3.0.2                         np22py313h9d9dc1e_0           emscripten-forge
+ python-tzdata                 2026.1                        pyhd8ed1ab_0                  conda-forge
- pip                           25.3                          pyh145f28c_0                  conda-forge

In [1]:
!pip install numpy

mambajs 0.19.13

Process pip requirements ...

Requirement numpy already handled by conda/micromamba/mamba.

In [3]:
import pandas as pd
import numpy as np

In [4]:
df =pd.read_csv('Cleanable.csv',sep = '\t')

In [6]:
df['Country'] = df['Country'].astype('category')

In [7]:
df.head()

   ID    Name   Age    Country                Email
0   1  Name_1  62.0  Country_1  email_1@example.com
1   2  Name_2  48.0  Country_2                  NaN
2   3  Name_3  61.0  Country_3  email_3@example.com
3   4  Name_4  32.0  Country_4  email_4@example.com
4   5  Name_5  69.0  Country_5  email_5@example.com

In [10]:
#Sorting Data by age in asceding order

df_sort = df.sort_values(by = ['Age','Country'], ascending = [True,False])

In [11]:
df_sort.head()

    ID     Name   Age    Country                 Email
65  66  Name_66  18.0  Country_6  email_66@example.com
13  14  Name_14  18.0  Country_4  email_14@example.com
57  58  Name_58  19.0  Country_8  email_58@example.com
67  68  Name_68  19.0  Country_8  email_68@example.com
89  90  Name_90  19.0        NaN  email_90@example.com

In [13]:
#Ranking the Data

df['sales_rank'] = df.groupby('Country')['Age'].rank(method = 'dense', ascending = False)
print("\nAge Rank within Country Groups\n", df)

Age Rank within Country Groups
      ID      Name   Age    Country                  Email  sales_rank
0     1    Name_1  62.0  Country_1    email_1@example.com         2.0
1     2    Name_2  48.0  Country_2                    NaN         5.0
2     3    Name_3  61.0  Country_3    email_3@example.com         1.0
3     4    Name_4  32.0  Country_4    email_4@example.com         5.0
4     5    Name_5  69.0  Country_5    email_5@example.com         1.0
..  ...       ...   ...        ...                    ...         ...
95   96   Name_96  60.0  Country_6   email_96@example.com         3.0
96   97   Name_97  26.0  Country_7                    NaN         8.0
97   98   Name_98  52.0  Country_8   email_98@example.com         3.0
98   99   Name_99  24.0  Country_9   email_99@example.com        10.0
99  100  Name_100  55.0  Country_0  email_100@example.com         3.0

[100 rows x 6 columns]

In [16]:
#Joining ang Merging Data

customers = pd.DataFrame({
    'CustomerID': [1, 2, 3],
    'Name' : ['John', 'Jane', 'Joe']
})

orders = pd.DataFrame({
    'OrderID' : [101, 102, 103, 104],
    'CustomerID' : [1,2,2,3],
    'Amount' : [250, 150, 100, 300]
})

In [17]:
# Inner Merge on CustomerID

df_inner = pd.merge(customers, orders, on = 'CustomerID', how = 'inner')
print("Inner Merge\n", df_inner)

Inner Merge
    CustomerID  Name  OrderID  Amount
0           1  John      101     250
1           2  Jane      102     150
2           2  Jane      103     100
3           3   Joe      104     300

In [18]:
# Left Merge
df_left = pd.merge(customers, orders, on = 'CustomerID', how = 'left')
print("Left Merge\n", df_left)

Left Merge
    CustomerID  Name  OrderID  Amount
0           1  John      101     250
1           2  Jane      102     150
2           2  Jane      103     100
3           3   Joe      104     300

In [20]:
# Concatinate the Data
df_conc= pd.concat([customers, customers])
print("Concatinated datae\n", df_conc)

Concatinated datae
    CustomerID  Name
0           1  John
1           2  Jane
2           3   Joe
0           1  John
1           2  Jane
2           3   Joe

In [21]:
df = pd.read_csv('ecommerce_sales_analytics_5000.csv', parse_dates = ['order_date'])

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          5000 non-null   int64
 1   order_date        5000 non-null   datetime64[us]
 2   customer_id       5000 non-null   int64
 3   product_category  5000 non-null   str
 4   region            5000 non-null   str
 5   quantity          5000 non-null   int64
 6   unit_price        5000 non-null   float64
 7   discount          5000 non-null   float64
 8   payment_method    5000 non-null   str
 9   delivery_days     5000 non-null   int64
 10  customer_rating   5000 non-null   float64
 11  revenue           5000 non-null   float64
dtypes: datetime64[us](1), float64(4), int64(4), str(3)
memory usage: 410.2 KB

In [27]:
#map function
#applied on a single column
#fast

df['paytype'] = df['payment_method'].map({
    'Card': 'Digital',
    'Wallet': 'Digital',
    'COD': 'Cash'
})

In [28]:
df['paytype'].unique()

<StringArray>
['Digital', 'Cash']
Length: 2, dtype: str

In [30]:
df[['paytype','payment_method']].head()

   paytype payment_method
0  Digital         Wallet
1  Digital           Card
2     Cash            COD
3  Digital         Wallet
4  Digital         Wallet

In [31]:
df.groupby('paytype').size()

paytype
Cash       1774
Digital    3226
dtype: int64

In [33]:
#Apply function
#can be applied on multiple columns
#slower then map

def rev_cat(row):
    if row['revenue'] > 500:
        return 'High'
    if row['revenue'] >= 200:
        return 'Medium'
    else:
        return 'Low'

df['rev_cat'] = df.apply(rev_cat, axis = 1)

In [35]:
df['rev_cat'].value_counts()

rev_cat
High      3252
Medium    1098
Low        650
Name: count, dtype: int64

In [37]:
df[['rev_cat','revenue']].sample(10)

     rev_cat  revenue
3278    High  1225.18
1743  Medium   334.87
1133    High  2641.78
689     High  1174.01
1812    High  1294.69
1429  Medium   478.72
1212     Low   160.91
201     High  3023.48
933      Low   127.74
2112    High   660.36

In [40]:
def add_profit(data):
    data['profit'] = data['revenue'] * 0.20
    return data

def addNetrev(data):
    data['net_rev'] = data['revenue'] - data['profit']
    return data

df = (
    df.pipe(add_profit).pipe(addNetrev)
)

In [41]:
df[['revenue','profit','net_rev']].head()

   revenue   profit   net_rev
0  1883.20  376.640  1506.560
1   304.10   60.820   243.280
2   644.35  128.870   515.480
3  2569.90  513.980  2055.920
4   468.56   93.712   374.848

In [42]:
df["order_date"] = pd.to_datetime(df["order_date"])

In [44]:
df.shape

(5000, 17)

In [45]:
df = pd.read_csv(
    'ecommerce_sales_analytics_5000.csv',
    parse_dates = ['order_date']
)

In [46]:
df.shape

(5000, 12)

In [47]:
df.describe()

,order_id,order_date,customer_id,quantity,unit_price,discount,delivery_days,customer_rating,revenue
count,5000.000000,5000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,12500.500000,2028-11-04 12:00:00,1505.701200,4.044800,308.418774,0.179984,6.118800,2.973980,1021.955148
min,10001.000000,2022-01-01 00:00:00,1000.000000,1.000000,15.150000,0.000000,1.000000,1.000000,11.210000
25%,11250.750000,2025-06-03 18:00:00,1253.000000,2.000000,161.895000,0.090000,3.000000,2.000000,354.527500
50%,12500.500000,2028-11-04 12:00:00,1510.000000,4.000000,309.890000,0.180000,6.000000,3.000000,796.650000
75%,13750.250000,2032-04-07 06:00:00,1761.000000,6.000000,455.557500,0.270000,9.000000,4.000000,1515.690000
max,15000.000000,2035-09-09 00:00:00,1999.000000,7.000000,599.960000,0.350000,11.000000,5.000000,4119.330000
std,1443.520003,NaN,290.836902,2.020398,169.259369,0.101404,3.153264,1.157722,825.584219

In [49]:
df['revenue'].quantile([0.25, 0.5, 0.75])

0.25     354.5275
0.50     796.6500
0.75    1515.6900
Name: revenue, dtype: float64

In [51]:
df['revenue'].mean(), df['revenue'].median()

(np.float64(1021.955148), np.float64(796.65))

In [52]:
df['revenue'].skew() #Right Skew

np.float64(1.0017064603000962)

In [53]:
df.groupby('product_category')['revenue'].describe()

,count,mean,std,min,25%,50%,75%,max
product_category,,,,,,,,
Beauty,723.0,1059.281992,867.590231,20.94,331.585,821.64,1662.825,4005.93
Clothing,1531.0,1000.608570,806.210745,11.21,349.940,785.22,1477.230,3928.63
Electronics,1777.0,1029.768835,831.796825,13.26,365.670,796.49,1499.280,4119.33
Home,969.0,1013.502497,812.271060,13.01,348.350,802.83,1488.750,3640.56

In [54]:
df.groupby('product_category')['revenue'].mean() #mean revenue by the product category

product_category
Beauty         1059.281992
Clothing       1000.608570
Electronics    1029.768835
Home           1013.502497
Name: revenue, dtype: float64

In [57]:
Q1 = df['revenue'].quantile(0.25)
Q3 = df['revenue'].quantile(0.75)
IQR = Q3 - Q1

Q1, Q3, IQR

(np.float64(354.5275), np.float64(1515.69), np.float64(1161.1625000000001))

In [58]:
(Q3 > Q1) and (IQR >0)

np.True_

In [59]:
df = df.set_index("order_date")

In [60]:
df.index

DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06', '2022-01-07', '2022-01-08',
               '2022-01-09', '2022-01-10',
               ...
               '2035-08-31', '2035-09-01', '2035-09-02', '2035-09-03',
               '2035-09-04', '2035-09-05', '2035-09-06', '2035-09-07',
               '2035-09-08', '2035-09-09'],
              dtype='datetime64[us]', name='order_date', length=5000, freq=None)

In [61]:
monthly_rev = df['revenue'].resample("ME").sum()
monthly_rev

order_date
2022-01-31    35624.89
2022-02-28    29908.89
2022-03-31    30309.28
2022-04-30    30781.96
2022-05-31    41629.24
                ...
2035-05-31    33393.87
2035-06-30    25205.26
2035-07-31    23944.48
2035-08-31    29354.74
2035-09-30     4952.23
Freq: ME, Name: revenue, Length: 165, dtype: float64

In [62]:
monthly_rev.pct_change()

order_date
2022-01-31         NaN
2022-02-28   -0.160450
2022-03-31    0.013387
2022-04-30    0.015595
2022-05-31    0.352391
                ...
2035-05-31    0.201727
2035-06-30   -0.245213
2035-07-31   -0.050021
2035-08-31    0.225950
2035-09-30   -0.831297
Freq: ME, Name: revenue, Length: 165, dtype: float64

In [64]:
monthly_rev.index.is_monotonic_increasing

True

In [65]:
print(monthly_rev.sum(),df['revenue'].sum())
monthly_rev.sum() <= df['revenue'].sum()

5109775.74 5109775.74

np.True_